### ISSUE TITLE
Open all x bookmarks opens only the first

### ISSUE THREAD

**Issue by w4grfw** [SamHH/bukubrow-webext#125]
When you press the icon “open all x bookmarks” only the first bookmark opens and not all filtered.

Chrome 80.0.3987.87
Bukurow 5.0.0.2

**Comment by SamHH** [comment]
Only affects Chrome, not Firefox. Will investigate this weekend.

**Comment by SamHH** [comment]
This has already been unintentionally fixed at some point on master! I suspect [here](https://github.com/SamHH/bukubrow-webext/commit/462ea20017e13dfc708bbba63ebe55531c47fdef), but I can't say for sure as there have been a lot of commits since the last release.

I'll publish a new release later today.

**Comment by SamHH** [comment]
Hey @w4grfw, a new release has just been published, it should be available for you shortly. Let me know if you continue to experience any problems. :slightly_smiling_face:
