### ISSUE TITLE
Binary distributions (AUR, Homebrew & other packages)

### ISSUE THREAD

**Issue by SamHH** [SamHH/bukubrow-webext#85]
See [browserpass](https://github.com/browserpass/browserpass#installing-the-host-application). I'd like to at least target Arch (AUR) and Homebrew initially.

**Comment by m040601** [comment]
Hi there, thank you for effort in this (very much essential) add on to Buku for Firefox(or Chrome) users. 

I was just about to open a new issue regarding an AUR package for Archlinux, then I saw, this same issue opend by you
1. Could you add "AUR package" and Homebrew to this issue  title line ?

This issue is in fact an important one, I think.
As a qutebrowser user one is already able to integrate quite well with Buku (and dmenu/rofi etc).Buku alone is great, but it is this "glueing" it together with Firefox (Dmenu/Rofi etc ) that makes it exponentially more usefull. The sum is much more than the individual parts. It would make it much much more attractive to a potential user.
The "problem" is this,
>  "registering it with your browser through the installation script is required to allow the browser extension to talk to Buku. 

Nobody will ever want to run install.sh/sudo scripts, bypass your system package manager and "pollute" your system just to give this extension a try.


I also saw another closed issue from 2017 "clarification about install.sh · Issue #41" by user "ghost", https://github.com/ghost.
> I'll try to put an aur package together, if you are interested to it i can post here when is done.
This was in 2017, so I assume this user "ghost" is no longer working on it ?


I'm an heavy Archlinux user, although I have never tryied to create an AUR package. My skills are somewhat limited but I am willing to contribute the best I can. 

2. Are you currently working on this yourself ? Maybe one could also post some request for help on the Arch Forums bbs.archlinux.org ?

Anyway, I'm gonna go now study how browserpass does it and how they created the AUR packages. I found this for the extension and the "registration". 

https://aur.archlinux.org/packages/browserpass-bin/
aur/browserpass-bin 2.0.21-1 (+0 0.00%) 
    Chrome & Firefox browser extension for pass, a UNIX password manager    

https://aur.archlinux.org/packages/firefox-browserpass/                        
aur/firefox-browserpass 2.0.22-0 (+2 0.58%) 
    A Firefox extension to retrieve login details from zx2c4 pass                                   

https://aur.archlinux.org/packages/browserpass-git/
aur/browserpass-git 1.0.2.r33.51579bc-1 (+2 0.00%)                                                  
    Chrome & Firefox browser extension for pass, a UNIX password manager     
                       
https://aur.archlinux.org/packages/browserpass
aur/browserpass 2.0.21-2 (+36 2.46%) 
    Chrome & Firefox browser extension for pass, a UNIX password manager

**Comment by m040601** [comment]
In addition to browserpass, https://github.com/browserpass/browserpass

There is also passff, https://github.com/passff/passff
It is also recommended from the official pass developer page, https://www.passwordstore.org/

There are AUR packages both for the extension (firefox-passff) and the host application (passff-host),
https://aur.archlinux.org/packages/?O=0&SeB=nd&K=passff&outdated=&SB=n&SO=a&PP=50&do_Search=Go

**Comment by SamHH** [comment]
Thanks for the research! I've updated the issue title for clarity.

I run a setup very similar to your own, Arch and very dmenu/rofi-heavy, so AUR at least would be great for me. It's just a matter of time. I'm working on a couple of small bits for `2.6.0` at the moment.

If you find the time to make this happen in the AUR yourself let me know if I can help.

**Comment by paulie-g** [comment]
The complicating factor is that we simply don't know, without user interaction, where the native messaging enabling configs need to go. I run profiles in Chromium and they needed to go in the profile-specific dirs, which I had to do manually.

Don't get me wrong, I think an improved installation experience for vanilla configs would be great. With that said, AUR != extra/community. You're supposed to look at the PKGBUILDs and potentially do things to make everything work. The fact most people don't is beside the point.

Also, same here - rofi-heavy, use qutebrowser/Falkon/Chromium situationally. I actually have a script that lets me select tags with rofi + bookmark url in clipboard with a hotkey configured in openbox.

**Comment by SamHH** [comment]
What is [browserpass](https://www.archlinux.org/packages/community/x86_64/browserpass/) doing?

**Comment by SamHH** [comment]
The PR isn't quite ready yet, but #111 should go a long way towards making this happen. It allows you to install/register the browser hosts from the binary itself, so all you do is download the binary and run it with e.g. `bukubrow --install-firefox` and you're off.

This means that with package managers, as long as Bukubrow is in the PATH, you can install it and display a message telling the user that they now need to register it themselves, and to check out the options available with `bukubrow -h`.

:smile:

**Comment by SamHH** [comment]
Continue discussion here: https://github.com/SamHH/bukubrow-host/issues/3

**Comment by m040601** [comment]
> What is browserpass doing?
Another extension worth studying to see how they do things is
https://github.com/persepolisdm/Persepolis-WebExtension

Persepolis itself, https://github.com/persepolisdm/persepolis,
is just a great gui to the aria2c download manager.
So this all makes a great open source "download manager/interceptor" solution for firefox.

So just like browserpass and  buku we have 3 pieces of the puzzle:
- the application itself (pass, buku or aria2)
- the "host" or "native" glue (browserpass-native, bukubrow-host)
- the browser extension (browserpass-extension, bukubrow-extension)

The subtle thing needed is for this "registering" the extension. I  personally am against trying to to this on a system level. Trying to mess with the users system writing to /usr/lib/mozilla/native-messaging-hosts with complicated install.sh scripts.

Let's try concentrating on the users home dir.
$HOME/.mozilla/native-messaging-hosts/
a file called, com.XYZ.ABC.json, has to be created containing a pointer to the binary

Right now, bukubrow (host) needs this additional step to do that:
bukubrow --install-firefox

With https://github.com/persepolisdm/Persepolis-WebExtension this step is not needed.
Just by installing the extension from Mozilla addons it does this for you.
That is a file called, com.persepolis.XYZ.json is created in $HOME/.mozilla/native-messaging-hosts/ pointing to the standard persepolis binary location
